name: test & release

on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install-deps
      - run: npx playwright install
      # Ensure tests are not flaky
      - run: npm run test
      - run: npm run test
      # ...
      - run: npm run test -- --coverage
      - uses: codecov/codecov-action@v3
      - run: npm run build
      - run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
