name: test & release

on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install --with-deps
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test -- --coverage
