name: test & release

on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 14
      - run: npm ci
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm test
